### ISSUE TITLE
About the thread.c set_priority and get_priority

### ISSUE THREAD

**Issue by Eric-Miao** [dillstead/pintos#1]
hi, there.
In proj1, set_priority and get_priority are only called during the priority_sechduler, not the advanced scheduler and further should be banned if the option for the advanced scheduler is set. Is there a missing understanding for me?

**Comment by dillstead** [comment]
Nope, you're right.  They are not applicable and should not be called when the advanced scheduler is compiled in.  I should put a guard to return immediately in this case.  Apologies for the late reply.
